### ISSUE TITLE
DB is missing

### ISSUE THREAD

**Issue by Imranjunnaid** [quantumstrings/GPS-Listener-Parser#2] opened 2019-01-05 20:00 UTC
dear please share the db schema as well or db backup file for execute and test run

**Comment by grmkris** [comment] 2019-04-03 14:47
yes please i need db schema aswell

**Comment by GeorgeMihalache** [comment] 2019-04-04 19:15
me to please

**Comment by grmkris** [comment] 2019-04-05 07:49
I managed to remove db requirement and instead I write to output file as a .csv
would you be interested? I can upload fixed version on my profile

**Comment by SpaceQuantum** [comment] 2019-04-05 08:43
> I managed to remove db requirement and instead I write to output file as a .csv
> would you be interested? I can upload fixed version on my profile

You can fork and upload version of csv store provider of course,
About db schema, I will add db schema and updated provider to project before end of this week, because I very busy now.
I currently not have a Teltonika device for testing and it would be nice if someone from you write feedback after test updated version after it will updated.

**Comment by grmkris** [comment] 2019-04-05 09:17
thanks for your response @quantumstrings . I am not that familiar with C# so I just did a little hack of commenting out the database code and replacing it with filesaver functionality. I'd like to connect to oracle database or MS access database could you give me any pointers how to do that?  
When you have new version uploaded here on github I'll gladly test it with teltonika device

**Comment by grmkris** [comment] 2019-04-10 12:41
hey @quantumstrings I have another questions. I got told that device consumes quite a lot of data. I was  told that is because server is closing connections. Could you give me some pointers how would I open connection to the device and keep the connection open.

**Comment by SpaceQuantum** [comment] 2019-04-10 13:09
Hi @grmkris, this parser leaves the socket open until an exception occurs or the device accepts and receive all data, but you can try comment code on AsynchronousIoServer.cs line 185 where connection is closed after receive all data. It may cause leakage of open sockets. You need close unused connection after some timeout, maybe few hours for example.

**Comment by grmkris** [comment] 2019-04-10 18:11
@quantumstrings thank you for taking your time helping me.
Yes I commented that line out. but as I understand every time we receive data new connection is opened? is that right?  
I was told that this consumes a lot of data (40mb in 3 days if i remember correctly) and that the problem is supposedly in the server... something with closing connections.
This is my 1st time dealing with c# so I am a bit slow to understand how everything works, thanks for your patience.

**Comment by SpaceQuantum** [comment] 2019-04-12 11:11
> @quantumstrings thank you for taking your time helping me.
> Yes I commented that line out. but as I understand every time we receive data new connection is opened? is that right?

Yes. Seems you need remove BeginAccept after BeginReceive for prevent open new connection, because you commented close connection code line.

About consumes a lot of data, to determine the reason you probably need to use WireShark or something like this for analyze traffic and find the real reason.

**Closed as completed** 2019-04-12 11:11 UTC
